[workspace]
channels = ["conda-forge"]
name = "jetable"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipython = ">=9.2.0,<10"
pandas = ">=2.2.3,<3"
pyspark = ">=3.5.5,<4"

[pypi-dependencies]
dxpy = ">=0.396.0, <0.397"
looseversion = ">=1.3.0, <2"
